package postgres

import (
	"context"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
)

// Querier is generated by sqlc.
type Querier interface {
	// Entitlements
	GetEntitlementByUserAndSource(ctx context.Context, userID string, source string) (Entitlement, error)
	GetEntitlementsByUser(ctx context.Context, userID string) ([]Entitlement, error)
	UpsertEntitlement(ctx context.Context, userID string, source string, active bool, expiresAt interface{}, reason interface{}, lastEventTime int64) error
	UpdateEntitlementCarrierPolledAt(ctx context.Context, userID string, source string) error
	GetLastEventTimeFromStore(ctx context.Context, userID string) (int64, error)
	GetEntitlementsExpiringWithin24h(ctx context.Context) ([]Entitlement, error)
	GetCarrierEntitlementsForPolling(ctx context.Context, limit int32) ([]Entitlement, error)

	// Store Events
	InsertStoreEvent(ctx context.Context, eventID string, userID string, eventType string, eventTimeMs int64, productID interface{}) error
	GetStoreEventsByUser(ctx context.Context, userID string) ([]StoreEvent, error)
	GetStoreEventByID(ctx context.Context, eventID string) (StoreEvent, error)

	// Marketplace Revocations
	InsertMarketplaceRevocation(ctx context.Context, eventID string, userID string) error
	GetMarketplaceRevocationByEventID(ctx context.Context, eventID string) (MarketplaceRevocation, error)

	// Processed Events
	IsEventProcessed(ctx context.Context, eventID string, source string) (bool, error)
	MarkEventProcessed(ctx context.Context, eventID string, source string) error
	GetProcessedEvent(ctx context.Context, eventID string, source string) (ProcessedEvent, error)

	// Notifications
	ScheduleNotification(ctx context.Context, userID string, notificationType string, scheduledFor interface{}) error
	GetDueNotifications(ctx context.Context, limit int32) ([]Notification, error)
	MarkNotificationSent(ctx context.Context, id int64) error
	GetNotificationByUserTypeAndDate(ctx context.Context, userID string, notificationType string, date interface{}) (Notification, error)

	// Audit Logs
	InsertAuditLog(ctx context.Context, userID string, source string, previousActive interface{}, nextActive bool, previousExpiresAt interface{}, nextExpiresAt interface{}, triggeringEventID interface{}, reason interface{}) error
	GetAuditLogsByUser(ctx context.Context, userID string, limit int32, offset int32) ([]AuditLog, error)
	CountAuditLogsByUser(ctx context.Context, userID string) (int64, error)
}

// Client wraps database operations.
type Client struct {
	pool    *pgxpool.Pool
	queries Querier
}

// NewClient creates a new database client.
func NewClient(pool *pgxpool.Pool, queries Querier) *Client {
	return &Client{
		pool:    pool,
		queries: queries,
	}
}

// Connect creates a connection pool to the database.
func Connect(ctx context.Context, dsn string) (*Client, error) {
	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		return nil, fmt.Errorf("failed to create pool: %w", err)
	}

	// Test connection
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("failed to ping database: %w", err)
	}

	// TODO: Replace with generated queries struct
	var queries Querier
	
	return NewClient(pool, queries), nil
}

// Close closes the database connection pool.
func (c *Client) Close() {
	if c.pool != nil {
		c.pool.Close()
	}
}

// Health checks if the database is healthy.
func (c *Client) Health(ctx context.Context) error {
	return c.pool.Ping(ctx)
}

// Implement EntitlementRepository
func (c *Client) GetEntitlementByUserAndSource(ctx context.Context, userID string, source string) (*Entitlement, error) {
	ent, err := c.queries.GetEntitlementByUserAndSource(ctx, userID, source)
	if err != nil {
		return nil, err
	}
	return &ent, nil
}

func (c *Client) GetEntitlementsByUser(ctx context.Context, userID string) ([]Entitlement, error) {
	return c.queries.GetEntitlementsByUser(ctx, userID)
}

func (c *Client) UpsertEntitlement(ctx context.Context, userID string, source string, active bool, expiresAt *time.Time, reason *string, lastEventTime int64) error {
	return c.queries.UpsertEntitlement(ctx, userID, source, active, expiresAt, reason, lastEventTime)
}

func (c *Client) UpdateEntitlementCarrierPolledAt(ctx context.Context, userID string, source string) error {
	return c.queries.UpdateEntitlementCarrierPolledAt(ctx, userID, source)
}

func (c *Client) GetLastEventTimeFromStore(ctx context.Context, userID string) (int64, error) {
	return c.queries.GetLastEventTimeFromStore(ctx, userID)
}

func (c *Client) GetEntitlementsExpiringWithin24h(ctx context.Context) ([]Entitlement, error) {
	return c.queries.GetEntitlementsExpiringWithin24h(ctx)
}

func (c *Client) GetCarrierEntitlementsForPolling(ctx context.Context, limit int32) ([]Entitlement, error) {
	return c.queries.GetCarrierEntitlementsForPolling(ctx, limit)
}

// Implement StoreEventRepository
func (c *Client) InsertStoreEvent(ctx context.Context, eventID string, userID string, eventType string, eventTimeMs int64, productID *string) error {
	return c.queries.InsertStoreEvent(ctx, eventID, userID, eventType, eventTimeMs, productID)
}

func (c *Client) GetStoreEventsByUser(ctx context.Context, userID string) ([]StoreEvent, error) {
	return c.queries.GetStoreEventsByUser(ctx, userID)
}

func (c *Client) GetStoreEventByID(ctx context.Context, eventID string) (*StoreEvent, error) {
	evt, err := c.queries.GetStoreEventByID(ctx, eventID)
	if err != nil {
		return nil, err
	}
	return &evt, nil
}

// Implement MarketplaceRevocationRepository
func (c *Client) InsertMarketplaceRevocation(ctx context.Context, eventID string, userID string) error {
	return c.queries.InsertMarketplaceRevocation(ctx, eventID, userID)
}

func (c *Client) GetMarketplaceRevocationByEventID(ctx context.Context, eventID string) (*MarketplaceRevocation, error) {
	rev, err := c.queries.GetMarketplaceRevocationByEventID(ctx, eventID)
	if err != nil {
		return nil, err
	}
	return &rev, nil
}

// Implement ProcessedEventRepository
func (c *Client) IsEventProcessed(ctx context.Context, eventID string, source string) (bool, error) {
	return c.queries.IsEventProcessed(ctx, eventID, source)
}

func (c *Client) MarkEventProcessed(ctx context.Context, eventID string, source string) error {
	return c.queries.MarkEventProcessed(ctx, eventID, source)
}

func (c *Client) GetProcessedEvent(ctx context.Context, eventID string, source string) (*ProcessedEvent, error) {
	pe, err := c.queries.GetProcessedEvent(ctx, eventID, source)
	if err != nil {
		return nil, err
	}
	return &pe, nil
}

// Implement NotificationRepository
func (c *Client) ScheduleNotification(ctx context.Context, userID string, notificationType string, scheduledFor time.Time) error {
	return c.queries.ScheduleNotification(ctx, userID, notificationType, scheduledFor)
}

func (c *Client) GetDueNotifications(ctx context.Context, limit int32) ([]Notification, error) {
	return c.queries.GetDueNotifications(ctx, limit)
}

func (c *Client) MarkNotificationSent(ctx context.Context, id int64) error {
	return c.queries.MarkNotificationSent(ctx, id)
}

func (c *Client) GetNotificationByUserTypeAndDate(ctx context.Context, userID string, notificationType string, date time.Time) (*Notification, error) {
	notif, err := c.queries.GetNotificationByUserTypeAndDate(ctx, userID, notificationType, date)
	if err != nil {
		return nil, err
	}
	return &notif, nil
}

// Implement AuditLogRepository
func (c *Client) InsertAuditLog(ctx context.Context, userID string, source string, previousActive *bool, nextActive bool, previousExpiresAt *time.Time, nextExpiresAt *time.Time, triggeringEventID *string, reason *string) error {
	return c.queries.InsertAuditLog(ctx, userID, source, previousActive, nextActive, previousExpiresAt, nextExpiresAt, triggeringEventID, reason)
}

func (c *Client) GetAuditLogsByUser(ctx context.Context, userID string, limit int32, offset int32) ([]AuditLog, error) {
	return c.queries.GetAuditLogsByUser(ctx, userID, limit, offset)
}

func (c *Client) CountAuditLogsByUser(ctx context.Context, userID string) (int64, error) {
	return c.queries.CountAuditLogsByUser(ctx, userID)
}
